-- ROLE --
INSERT INTO roles(name,"createdAt","updatedAt") values('vendeur',CURRENT_DATE,CURRENT_DATE);
INSERT INTO roles(name,"createdAt","updatedAt") values('acheteur',CURRENT_DATE,CURRENT_DATE);
INSERT INTO roles(name,"createdAt","updatedAt") values('admin',CURRENT_DATE,CURRENT_DATE);

-- USER --
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('nathan38','nathan','hugon','azerty','nathan.nathan@gmail.com',1,'2000-01-01',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('milo73','milo','niemaz','123456','milo.olim@gmail.com',0,'2001-12-25',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('etienne93','etienne','chazelle','poiuy','eti.enne@gmail.com',2,'2003-11-03',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('lilian22','lilian','gardon','zqsd','lil.yann@gmail.com',0,'2003-03-01',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('adrien_le_ouf','adrien','ligne','ytreza','adrien.ad@gmail.com',1,'2002-06-29',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('marie_dupont','marie','dupont','motdepasse','marie.dupont@gmail.com',0,'1990-01-01',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('paul_henry','paul','henry','motdepasse','paul.henry@gmail.com',0,'1985-03-15',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('julie_martin','julie','martin','motdepasse','julie.martin@gmail.com',0,'1995-09-30',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('lucie_dufour','lucie','dufour','motdepasse','lucie.dufour@gmail.com',0,'2000-05-12',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('antoine_lefebvre','antoine','lefebvre','motdepasse','antoine.lefebvre@gmail.com',0,'1997-07-22',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('alexis_73','alexis','pretti','123abc','alexis.lebg@gmail.com',2,'2000-01-01',CURRENT_DATE,CURRENT_DATE,2);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('doigby_le_bg','doigby','porc','tuescapable','om.g@gmail.com',0,'1985-10-20',CURRENT_DATE,CURRENT_DATE,2);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('vladimirUwU','vladimir','patine','satan2','vladimir.ovitch@gmail.com',0,'1960-08-08',CURRENT_DATE,CURRENT_DATE,2);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('raymond01','raymond','roukmout','poooooooooo2','raie.mont@orange.fr',2,'1949-05-14',CURRENT_DATE,CURRENT_DATE,2);
INSERT INTO users(login,nom,prenom,password,email,nb_strikes,date_naiss,"createdAt","updatedAt","roleId") values('bob_la_saumure','bob','lemard','obo','bob.obo@gmail.com',1,'1999-01-10',CURRENT_DATE,CURRENT_DATE,3);

-- ARTICLE --
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('cardigan colore',30.0,'cardigan en laine d un troupeau de mouton de la creuse',CURRENT_DATE,CURRENT_DATE+1,'rouge,vert,jaune,bleu,rose','laine','M',40.0,CURRENT_DATE,1);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('t-shirt vert',5.0,'t-shirt de couleur verte en coton bio',CURRENT_DATE,CURRENT_DATE+1,'vert','coton','S',8.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('tricot vintage',10.0,'tricot de grand-mère iconique',CURRENT_DATE,CURRENT_DATE+1,'blanc','laine','XL',20.0,CURRENT_DATE,3);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('polaire recyclee',8.0,'polaire conçue avec des bouteilles en plastique recylees',CURRENT_DATE,CURRENT_DATE+1,'noir','polyester','L',15.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('foulard doux',75.0,'foulard en soie de grande qualite',CURRENT_DATE,CURRENT_DATE+1,'blanc,jaune,noir','soie','S',100.0,CURRENT_DATE,4);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chaussettes de Noël',10.0,'chaussettes pour les fêtes en cachemire',CURRENT_DATE,CURRENT_DATE+1,'blanc,rouge','cachemire','XS',18.0,CURRENT_DATE,5);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('pull en cachemire',40.0,'pull en cachemire pour les jours froids',CURRENT_DATE,CURRENT_DATE+1,'gris','cachemire','L',50.0,CURRENT_DATE,1);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('robe en dentelle',50.0,'robe en dentelle pour les soirées',CURRENT_DATE,CURRENT_DATE+1,'noir','dentelle','M',70.0,CURRENT_DATE,3);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chapeau de paille',15.0,'chapeau de paille pour les jours d été',CURRENT_DATE,CURRENT_DATE+1,'marron','paille','S',20.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('sac à main en cuir',70.0,'sac à main en cuir pour les occasions spéciales',CURRENT_DATE,CURRENT_DATE+1,'noir','cuir','M',100.0,CURRENT_DATE,4);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('gilet en laine',20.0,'gilet en laine pour les jours frais',CURRENT_DATE,CURRENT_DATE+1,'gris','laine','XL',30.0,CURRENT_DATE,5);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('jupe en lin',25.0,'jupe en lin pour les jours chauds',CURRENT_DATE,CURRENT_DATE+1,'blanc, marron','lin','S',40.0,CURRENT_DATE,1);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('veste en cuir',80.0,'veste en cuir pour les soirées en ville',CURRENT_DATE,CURRENT_DATE+1,'marron','cuir','M',120.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('écharpe en laine',20.0,'écharpe en laine pour les jours d hiver',CURRENT_DATE,CURRENT_DATE+1,'gris','laine','S',30.0,CURRENT_DATE,3);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chemise en coton',25.0,'chemise en coton pour les journées d été',CURRENT_DATE,CURRENT_DATE+1,'blanche','coton','L',40.0,CURRENT_DATE,4);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('short en jean',30.0,'short en jean pour les journées d été',CURRENT_DATE,CURRENT_DATE+1,'bleu','jean','S',40.0,CURRENT_DATE,5);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('pantalon en lin',40.0,'pantalon en lin pour les journées d été',CURRENT_DATE,CURRENT_DATE+1,'blanc','lin','M',60.0,CURRENT_DATE,1);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('soutien-gorge en dentelle',15.0,'soutien-gorge en dentelle pour les soirées spéciales',CURRENT_DATE,CURRENT_DATE+1,'noir','dentelle','S',20.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('pantalon en velours',40.0,'pantalon en velours pour les soirées habillées',CURRENT_DATE,CURRENT_DATE+1,'noir','velours','M',60.0,CURRENT_DATE,4);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('t-shirt à message',15.0,'t-shirt avec un message inspirant',CURRENT_DATE,CURRENT_DATE+1,'blanc','coton','L',20.0,CURRENT_DATE,5);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('robe en dentelle',50.0,'robe en dentelle pour les soirées de gala',CURRENT_DATE,CURRENT_DATE+1,'rouge','dentelle','S',70.0,CURRENT_DATE,6);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('pull en cachemire',40.0,'pull en cachemire pour les jours froids',CURRENT_DATE,CURRENT_DATE+1,'gris','cachemire','L',50.0,CURRENT_DATE,7);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('soutien-gorge en dentelle',15.0,'soutien-gorge en dentelle pour les soirées spéciales',CURRENT_DATE,CURRENT_DATE+1,'noir','dentelle','S',20.0,CURRENT_DATE,8);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('sac à main en cuir',70.0,'sac à main en cuir pour les occasions spéciales',CURRENT_DATE,CURRENT_DATE+1,'noir','cuir','M',100.0,CURRENT_DATE,9);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chapeau en feutre',25.0,'chapeau en feutre pour les jours d automne',CURRENT_DATE,CURRENT_DATE+1,'marron','feutre','S',35.0,CURRENT_DATE,10);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('écharpe en laine',20.0,'écharpe en laine pour les jours d hiver',CURRENT_DATE,CURRENT_DATE+1,'rouge','laine','L',30.0,CURRENT_DATE,1);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('veste en cuir',100.0,'veste en cuir pour un look élégant',CURRENT_DATE,CURRENT_DATE+1,'noir','cuir','L',120.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('sac à main en cuir',70.0,'sac à main en cuir pour les occasions spéciales',CURRENT_DATE,CURRENT_DATE+1,'marron','cuir','M',90.0,CURRENT_DATE,3);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('baskets en toile',40.0,'baskets en toile pour les jours actifs',CURRENT_DATE,CURRENT_DATE+1,'blanc,noir','toile','M',50.0,CURRENT_DATE,4);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('robe de soirée',90.0,'robe de soirée en dentelle pour les soirées de gala',CURRENT_DATE,CURRENT_DATE+1,'noir','dentelle','S',120.0,CURRENT_DATE,5);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chaussures en cuir',60.0,'chaussures en cuir pour les occasions spéciales',CURRENT_DATE,CURRENT_DATE+1,'marron','cuir','M',80.0,CURRENT_DATE,6);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('maillot de bain',30.0,'maillot de bain en élasthanne pour la plage',CURRENT_DATE,CURRENT_DATE+1,'bleu','élasthanne','M',40.0,CURRENT_DATE,7);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('cravate en soie',20.0,'cravate en soie pour les occasions professionnelles',CURRENT_DATE,CURRENT_DATE+1,'rouge','soie','S',30.0,CURRENT_DATE,8);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('t-shirt à imprimé graphique',15.0,'t-shirt à imprimé graphique pour un look décontracté',CURRENT_DATE,CURRENT_DATE+1,'noir','coton','M',20.0,CURRENT_DATE,9);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('lunettes de soleil en acétate',25.0,'lunettes de soleil en acétate pour se protéger les yeux',CURRENT_DATE,CURRENT_DATE+1,'noir','acétate','L',35.0,CURRENT_DATE,10);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chaussettes en laine',10.0,'chaussettes en laine pour les jours d hiver',CURRENT_DATE,CURRENT_DATE+1,'gris','laine','XS',15.0,CURRENT_DATE,1);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('épingles à cheveux en perles',15.0,'épingles à cheveux en perles pour les occasions spéciales',CURRENT_DATE,CURRENT_DATE+1,'blanc','perles','XS',20.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('collier en argent',50.0,'collier en argent pour un look élégant',CURRENT_DATE,CURRENT_DATE+1,'argent','argent','M',70.0,CURRENT_DATE,3);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('montre en acier',70.0,'montre en acier pour un look décontracté',CURRENT_DATE,CURRENT_DATE+1,'acier','acier','M',100.0,CURRENT_DATE,4);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chemise en coton',30.0,'chemise en coton pour un look décontracté',CURRENT_DATE,CURRENT_DATE+1,'blanche','coton','M',40.0,CURRENT_DATE,5);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('jupe en cuir',50.0,'jupe en cuir pour un look élégant',CURRENT_DATE,CURRENT_DATE+1,'noir','cuir','S',60.0,CURRENT_DATE,6);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('pantalon en lin',40.0,'pantalon en lin pour les jours d été',CURRENT_DATE,CURRENT_DATE+1,'blanc','lin','L',50.0,CURRENT_DATE,7);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('pull en laine',30.0,'pull en laine pour les jours frais',CURRENT_DATE,CURRENT_DATE+1,'gris','laine','M',40.0,CURRENT_DATE,8);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('robe en dentelle',50.0,'robe en dentelle pour les soirées de gala',CURRENT_DATE,CURRENT_DATE+1,'noir','dentelle','S',60.0,CURRENT_DATE,9);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('veste en cuir',70.0,'veste en cuir pour un look décontracté',CURRENT_DATE,CURRENT_DATE+1,'marron','cuir','L',80.0,CURRENT_DATE,10);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('pantalon en velours',50.0,'pantalon en velours pour un look élégant',CURRENT_DATE,CURRENT_DATE+1,'noir','velours','L',60.0,CURRENT_DATE,1);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('chemise en soie',40.0,'chemise en soie pour les occasions spéciales',CURRENT_DATE,CURRENT_DATE+1,'blanche','soie','M',50.0,CURRENT_DATE,2);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('robe en laine',60.0,'robe en laine pour les jours d hiver',CURRENT_DATE,CURRENT_DATE+1,'grise','laine','S',70.0,CURRENT_DATE,3);
INSERT INTO articles(titre,prix_depart,description,"createdAt",expires,couleurs,materiaux,taille,seuil_reserve,"updatedAt","vendeurId") values('blazer en lin',50.0,'blazer en lin pour les jours d été',CURRENT_DATE,CURRENT_DATE+1,'beige','lin','M',60.0,CURRENT_DATE,4);

-- ENCHERE --
INSERT INTO encheres(montant,date,"createdAt","updatedAt","userId","articleId") values(30.0,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,1,1);
INSERT INTO encheres(montant,date,"createdAt","updatedAt","userId","articleId") values(5.0,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,2,2);
INSERT INTO encheres(montant,date,"createdAt","updatedAt","userId","articleId") values(10.0,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,3,3);
INSERT INTO encheres(montant,date,"createdAt","updatedAt","userId","articleId") values(8.0,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,4,2);
INSERT INTO encheres(montant,date,"createdAt","updatedAt","userId","articleId") values(100.0,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,5,4);
INSERT INTO encheres(montant,date,"createdAt","updatedAt","userId","articleId") values(10.0,CURRENT_DATE,CURRENT_DATE,CURRENT_DATE,6,5);

-- IMAGE --
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://ags-live.cdn.aboutyou.cloud/images/7a45553a26c0498afe3e644a2e728584.jpg?brightness=1&width=768&height=1024&quality=75&bg=FFFFFF',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://ags-live.cdn.aboutyou.cloud/images/a14c8908f640ea05931656059f88aee1.jpg?brightness=1&width=768&height=1024&quality=75&bg=FFFFFF',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://ags-live.cdn.aboutyou.cloud/images/0781ea72bafce7639a3a75938f88e6a9.jpg?brightness=1&width=768&height=1024&quality=75&bg=FFFFFF',CURRENT_DATE,CURRENT_DATE,1);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://www.couleurdenuit.com/18225-thickbox_default/t-shirt-fluo-homme-vert.jpg',CURRENT_DATE,CURRENT_DATE,2);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://www.couleurdenuit.com/18224-thickbox_default/t-shirt-fluo-homme-vert.jpg',CURRENT_DATE,CURRENT_DATE,2);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://www.gabbavintage.com/wp-content/uploads/2022/01/COL-V-Pull-Vintage-80s-Mailles-Blanc-2.jpg',CURRENT_DATE,CURRENT_DATE,3);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://www.gabbavintage.com/wp-content/uploads/2022/01/COL-V-Pull-Vintage-80s-Mailles-Blanc-1.jpg',CURRENT_DATE,CURRENT_DATE,3);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://ntextil-a1a5.kxcdn.com/files/model_specifications/2022/8/31/1102398/1102398_big.jpg?1661929055',CURRENT_DATE,CURRENT_DATE,4);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://ntextil-a1a5.kxcdn.com/files/model_specifications/2022/8/31/1102398/1102398_left_big.jpg?1661929060',CURRENT_DATE,CURRENT_DATE,4);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://ntextil-a1a5.kxcdn.com/files/model_specifications/2022/8/31/1102398/1102398_back_big.jpg?1661929059',CURRENT_DATE,CURRENT_DATE,4);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://www.princessefoulard.com/11970-large_6_4/homme-luxe.jpg',CURRENT_DATE,CURRENT_DATE,5);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://www.princessefoulard.com/11967-large_6_4/homme-luxe.jpg',CURRENT_DATE,CURRENT_DATE,5);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://mafabriqueperso.fr/2819-large_default/chaussette-de-noel.jpg',CURRENT_DATE,CURRENT_DATE,6);
INSERT INTO images(url,"createdAt","updatedAt","articleId") values('https://mafabriqueperso.fr/2847-large_default/chaussette-de-noel.jpg',CURRENT_DATE,CURRENT_DATE,6);

-- REPORT --
INSERT INTO reports(motif,date,"createdAt","updatedAt") values('Ce t-shirt est offensant! il y a une inscription dessus qui est grossière!',CURRENT_DATE,CURRENT_DATE,CURRENT_DATE);

-- LIKES --

INSERT INTO likes("createdAt","updatedAt","userId","articleId") values(CURRENT_DATE,CURRENT_DATE,1,1);
INSERT INTO likes("createdAt","updatedAt","userId","articleId") values(CURRENT_DATE,CURRENT_DATE,3,1);
INSERT INTO likes("createdAt","updatedAt","userId","articleId") values(CURRENT_DATE,CURRENT_DATE,2,1);
INSERT INTO likes("createdAt","updatedAt","userId","articleId") values(CURRENT_DATE,CURRENT_DATE,1,2);